services:
    train:
        build:
            context: .
            dockerfile: Dockerfile
        command: python src/train.py
        image: megatron17/docker-lightning-101:latest
        volumes:
            - ./logs:/logs
            - ./data:/data
  
    evaluate:
        build:
            context: .
            dockerfile: Dockerfile
        command: python src/eval.py
        image: megatron17/docker-lightning-101:latest
        volumes:
            - ./logs:/logs
            - ./data:/data

    infer:
        build:
            context: .
            dockerfile: Dockerfile
        command: python src/infer.py
        image: megatron17/docker-lightning-101:latest
        volumes:
            - ./logs:/logs
            - ./data:/data
            - ./output:/output

    # create volumes here
volumes:
    logs:
    data:
    output: